### ISSUE TITLE
Remove "stop=" argument for compatibility with CircuitPython busio.I2C

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_BitbangIO#11]
To reflect the behavior of CircuitPython's busio.I2C, remove the "stop=" argument from the I2C.writeto() method, and always send a "stop" condition on the I2C bus at the end of a write: https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO/blob/master/adafruit_bitbangio.py#L124

See https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/issues/53

**Comment by makermelissa** [comment]
Fixed via #12.
