### ISSUE TITLE
Python 3.5 vs 3.8

### ISSUE THREAD

**Issue by plotti** [adafruit/Adafruit_CircuitPython_BitbangIO#19]
I really want to install this with python 3.5 but https://pypi.org/project/sysv-ipc now needs python 3.8, what is the latest version that runs with 3.5?

**Comment by makermelissa** [comment]
sysv-ipc actually just needs Python 3.6: http://semanchuk.com/philip/sysv_ipc/. I think the previous release of sysv-ipc used Python 3.5.

**Comment by plotti** [comment]
but even when i install version 1.0.0 it defaults back to sysv_ipc-1.1.0.tar.gz so somehow the dependencies are messed up?

**Comment by tannewt** [comment]
@plotti Please keep the language in issues on Adafruit repos PG. I've edited your comment to replace a word. Please see the Code of Conduct that we enforce over our repos. Thanks! https://github.com/adafruit/Adafruit_Community_Code_of_Conduct/blob/main/code-of-conduct.md
