### ISSUE TITLE
Pylint pinned to 1.9.2

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_BitbangIO#3]
Pylint is still pinned to 1.9.2. This needs to be updated to latest (not pinned) and any necessary changes made to the code.

@makermelissa I'm guessing you cookiecuttered this before we made the Pylint change. If you get a chance, please update it. Thanks!

**Comment by makermelissa** [comment]
Your guess is correct. Fix pushed.
