### ISSUE TITLE
Add I2C to Library

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_BitbangIO#6]
I2C would be a great addition to this library, so just creating an issue as a "To Do".

**Comment by ladyada** [comment]
https://stackoverflow.com/questions/54087839/how-to-fix-bugs-in-my-i2c-bit-bang-python-library

**Comment by ladyada** [comment]
http://pyi2c.sourceforge.net/

**Comment by makermelissa** [comment]
Thanks @ladyada

**Comment by declanshanaghy** [comment]
👍

**Comment by makermelissa** [comment]
Ok, after feeling like I've been bitbanging my head against a wall, I'm finally getting device scanning working successfully. I think that means a lot of the basics are in place and I should be getting some good communication going soon.

**Comment by makermelissa** [comment]
Now it's reading the Chip ID successfully. It's getting closer.

**Comment by makermelissa** [comment]
Ok, it is now communicating with a bme280 without errors. Data isn't correct, but that's just details.

**Comment by makermelissa** [comment]
The issues appears to be in my read function when reading multiple bytes. It reads the first byte and then it seems to get confused until the next write. I'm almost certain it has something to do with the NACK I'm giving it at the end. Sending ACK or just not sending it doesn't work at all.

**Comment by makermelissa** [comment]
Once I realized the difference between ACK and NACK I got it working great. Just for reference:
NACK = I got the data, but we're not done yet
ACK = We have all the data

**Comment by ladyada** [comment]
ok please start the draft pr :)

**Comment by makermelissa** [comment]
Fixed by #7
