### ISSUE TITLE
Add OneWire Support

### ISSUE THREAD

**Issue by themeadery** [adafruit/Adafruit_CircuitPython_BitbangIO#8]
Will Blinka ever support OneWire like the main fork of Circuit Python? I have a DS18B20 temp sensor and many hours have gone into trying to get it to work. I'm down to writing lots of code (bitbang?) from scratch at this point. It would be nice if busio or bitbingio modules had the OneWire code in them.

**Comment by ladyada** [comment]
kk we transfered it to bitbangio which is where this would live if we did implement it!

**Comment by evaherrada** [comment]
hi @phorensic Were you ever able to figure out how to get this working?

**Comment by themeadery** [comment]
The short answer is after many hours of hacking, no. I think I will try a thermistor based solution. Then I'm just reading voltages and doing math.
